// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxOyuS5NoiKvNESAagp4_WCrqZIgBfyEs',
    appId: '1:6540576529:android:6f9fcaed0013c02085eeb0',
    messagingSenderId: '6540576529',
    projectId: 'alzajeltravel-e67e1',
    storageBucket: 'alzajeltravel-e67e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx2xfrgbG1wa8ImUsdtEoVFsKJe-mOlZE',
    appId: '1:6540576529:ios:f91b8025502627f985eeb0',
    messagingSenderId: '6540576529',
    projectId: 'alzajeltravel-e67e1',
    storageBucket: 'alzajeltravel-e67e1.firebasestorage.app',
    iosBundleId: 'com.horizon.agents',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARTTQz-SuInDbNMmE2v8KwltAFc9pOCEM',
    appId: '1:6540576529:web:9a856acf4c9172d785eeb0',
    messagingSenderId: '6540576529',
    projectId: 'alzajeltravel-e67e1',
    authDomain: 'alzajeltravel-e67e1.firebaseapp.com',
    storageBucket: 'alzajeltravel-e67e1.firebasestorage.app',
  );

}